/*
IbClient

Testing RecordaAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package dns

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/unasra/nios-go-client/dns"
)

func TestRecordaAPIService(t *testing.T) {

	apiClient := dns.NewAPIClient()

	t.Run("Test RecordaAPIService Get", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RecordaAPI.Get(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RecordaAPIService Post", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RecordaAPI.Post(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RecordaAPIService RecordaReferenceDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var recordaReference string

		httpRes, err := apiClient.RecordaAPI.RecordaReferenceDelete(context.Background(), recordaReference).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RecordaAPIService RecordaReferenceGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var recordaReference string

		resp, httpRes, err := apiClient.RecordaAPI.RecordaReferenceGet(context.Background(), recordaReference).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RecordaAPIService RecordaReferencePut", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var recordaReference string

		resp, httpRes, err := apiClient.RecordaAPI.RecordaReferencePut(context.Background(), recordaReference).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
