/*
IbClient

Testing RecordaaaaAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package dns

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/unasra/nios-go-client/dns"
)

func TestRecordaaaaAPIService(t *testing.T) {

	apiClient := dns.NewAPIClient()

	t.Run("Test RecordaaaaAPIService Get", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RecordaaaaAPI.Get(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RecordaaaaAPIService Post", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RecordaaaaAPI.Post(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RecordaaaaAPIService RecordaaaaReferenceDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var recordaaaaReference string

		resp, httpRes, err := apiClient.RecordaaaaAPI.RecordaaaaReferenceDelete(context.Background(), recordaaaaReference).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RecordaaaaAPIService RecordaaaaReferenceGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var recordaaaaReference string

		resp, httpRes, err := apiClient.RecordaaaaAPI.RecordaaaaReferenceGet(context.Background(), recordaaaaReference).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RecordaaaaAPIService RecordaaaaReferencePut", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var recordaaaaReference string

		resp, httpRes, err := apiClient.RecordaaaaAPI.RecordaaaaReferencePut(context.Background(), recordaaaaReference).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
